name: "Build Image"
description: "Build and upload container image"
runs:
  using: "composite"
  steps:
    - name: Arch environment variable
      shell: bash
      run: |
        case $(uname -m) in
        x86_64)
            echo "ARCH=amd64" >> $GITHUB_ENV
            ;;
        aarch64)
            echo "ARCH=arm64" >> $GITHUB_ENV
            ;;
        *)
            echo "ARCH=$(uname -m)" >> $GITHUB_ENV
            ;;
        esac
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver-opts: |
          network=host
    - name: Operator
      uses: docker/build-push-action@v6
      with:
        push: true
        build-args: |
          TAG=${{ github.ref_name }}
          COMMIT=${{ github.sha }}
        tags: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}/cilium-egress-operator:${{ env.TAG }}-${{ env.ARCH }}
        platforms: "linux/${{ env.ARCH }}"
        file: package/Dockerfile
        target: operator
        sbom: true
        provenance: mode=max
