kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cilium-egress-operator
  namespace: cattle-system
rules:
  - apiGroups: ['']
    resources: ['secrets']
    verbs: ['get', 'list', 'create', 'watch']
  - apiGroups: ['cce.pandaria.io']
    resources: ['cceclusterconfigs']
    verbs: ['get', 'list', 'update', 'watch']
  - apiGroups: ['cce.pandaria.io']
    resources: ['cceclusterconfigs/status']
    verbs: ['update']
