apiVersion: apps/v1
kind: Deployment
metadata:
  name: cilium-egress-operator
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cilium-egress-operator
  template:
    metadata:
      labels:
        app: cilium-egress-operator
    spec:
      nodeSelector: {{ include "linux-node-selector" . | nindent 8 }}
      serviceAccountName: cilium-egress-operator
      {{- if .Values.priorityClassName }}
      priorityClassName: "{{.Values.priorityClassName}}"
      {{- end }}
      securityContext:
        fsGroup: 1007
        runAsUser: 1007
      containers:
      - name: cilium-egress-operator
        image: {{ template "system_default_registry" . }}{{ .Values.ciliumEgressOperator.image.repository }}:{{ .Values.ciliumEgressOperator.image.tag }}
        imagePullPolicy: IfNotPresent
        env:
        - name: HTTP_PROXY
          value: {{ .Values.httpProxy }}
        - name: HTTPS_PROXY
          value: {{ .Values.httpsProxy }}
        - name: NO_PROXY
          value: {{ .Values.noProxy }}
        - name: CATTLE_RESYNC_DEFAULT
          value: {{ .Values.ciliumEgressOperator.resyncDefault | quote }}
        - name: CATTLE_DEV_MODE
          value: {{ .Values.ciliumEgressOperator.debug | quote }}
