name: "Merge images manifests"
description: "Merge amd64 and arm64 images manifest into a single multi-arch manifest"
runs:
  using: "composite"
  steps:
    - name: Install Hangar
      uses: cnrancher/hangar/.github/actions/install-hangar@main
    - name: Merge operator manifest
      shell: bash
      run: |
        set -x
        hangar merge-manifest ${{ env.REGISTRY }}/${{ env.REPOSITORY }}/cilium-egress-operator:${{ env.TAG }} \
          ${{ env.REGISTRY }}/${{ env.REPOSITORY }}/cilium-egress-operator:${{ env.TAG }}-amd64 \
          ${{ env.REGISTRY }}/${{ env.REPOSITORY }}/cilium-egress-operator:${{ env.TAG }}-arm64

        hangar inspect docker://${{ env.REGISTRY }}/${{ env.REPOSITORY }}/cilium-egress-operator:${{ env.TAG }} --raw
