name: CI

on:
  pull_request:
  push:
    branches: [ '**' ]
    tags-ignore: [ '**' ] # Disable Tag

env:
  REGISTRY: "localhost:5000"
  REPOSITORY: "library"
  TAG: "dev"

jobs:
  golang-ci:
    runs-on: ${{ github.repository_owner == 'cnrancher' && 'org-cnrancher-runner-dind-x64' || 'ubuntu-latest' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.x
      - name: Lint
        uses: golangci/golangci-lint-action@v8
      - name: Validate
        run: |
          ./scripts/verify.sh
      - name: Go Test
        run: |
          ./scripts/test.sh
  image-build:
    runs-on: ${{ github.repository_owner == 'cnrancher' && 'org-cnrancher-runner-dind-x64' || 'ubuntu-latest' }}
    services:
      registry:
        image: registry.suse.com/suse/registry:2.8
        ports:
          - 5000:5000
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Image Build
        uses: ./.github/actions/image-release
