name: Release

on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    permissions:
      contents: write # required for creating GH release
    runs-on: ubuntu-latest
    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        registry: ${{ vars.PUBLIC_REGISTRY }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Login to TCR
      uses: docker/login-action@v3
      with:
        registry: ${{ vars.TCR_REGISTRY }}
        username: ${{ secrets.TCR_USERNAME }}
        password: ${{ secrets.TCR_TOKEN }}
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ github.ref_name}}
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.24.x
    - name: Lint
      uses: golangci/golangci-lint-action@v7
    - name: Verify
      run: |
        make verify
    - name: Test
      run: |
        make test
    - name: Go Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # required for creating GH release
        TAG: ${{ github.ref_name }}
        COMMIT: ${{ github.sha }}
      uses: goreleaser/goreleaser-action@v6
      with:
        distribution: goreleaser
        version: "~> v2"
        args: release --clean --verbose
    - name: Image Push DockerHub
      run: |
        make image-push
      env:
        TAG: ${{ github.ref_name }}
        REPO: ${{ vars.PUBLIC_REGISTRY }}/${{ vars.PUBLIC_REGISTRY_REPO }}
    - name: Image Push TCR
      run: |
        make image-push

        echo "${{ vars.TCR_REGISTRY }}/${{ vars.PUBLIC_REGISTRY_REPO }}/cilium-egress-operator:${{ github.ref_name }}" > images.txt
      env:
        TAG: ${{ github.ref_name }}
        REPO: ${{ vars.TCR_REGISTRY }}/${{ vars.PUBLIC_REGISTRY_REPO }}
    - name: Upload Charts
      env:
        TAG: ${{ github.ref_name }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # required for updating GH release
      run: |
        make chart
        for f in $(find dist/artifacts/ -name '*.tgz'); do
          echo "Uploading $f to GitHub release $TAG"
          gh release upload $TAG $f
        done
        echo "Charts successfully uploaded to GitHub release $TAG"
  image-sign:
    permissions:
      id-token: write # required for hangar sign OIDC keyless mode
    runs-on: ubuntu-latest
    needs: [ release ]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ github.ref_name}}
    - name: Login to TCR
      uses: docker/login-action@v3
      with:
        registry: ${{ vars.TCR_REGISTRY }}
        username: ${{ secrets.TCR_USERNAME }}
        password: ${{ secrets.TCR_TOKEN }}
    - name: Hangar Sign
      uses: cnrancher/hangar/.github/actions/hangar-sign@main
      with:
        images: |
          ${{ vars.TCR_REGISTRY }}/${{ vars.PUBLIC_REGISTRY_REPO }}/cilium-egress-operator:${{ github.ref_name }}
